version: '3.7'

networks:
  kong-net:
    external: true

services:
  gmsh:
    container_name: gmsh
    image: gmsh:latest
    build: ./services/gmsh-integration/
    restart: always
    networks: 
      - "kong-net"
    ports:
      - "6002:6002"
    environment:
      - PORT=6002
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 6002
  
  nlopt:
    container_name: nlopt
    image: nlopt:latest
    build: ./services/nlopt_integration/
    restart: always
    networks: 
      - "kong-net"
    ports:
      - "5000:5000"
    environment:
      - "PORT=5000"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 5000

  # electrosfi
  electrosfi:
    image: electrosfi-ui-prod:latest
    restart: always
    container_name: electrosfi-ui-prod
    build: ./services/electrosfi-base/electrosfi-master/
    networks: 
      - "kong-net"
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    volumes:
      - "./services/electrosfi-base/electrosfi-master/resources/default.conf.template:/etc/nginx/conf.d/default.conf.template"
      - "./services/electrosfi-base/electrosfi-master/resources/default.conf.template:/etc/nginx/conf.d/default.conf"
      - "./services/electrosfi-base/electrosfi-master/resources/nginx.conf:/etc/nginx/nginx.conf"

  #electrosfi backend
  mongodb:
    image: mongo
    restart: always
    networks:
      - "kong-net"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    networks:
      - "kong-net"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_URL=mongodb://root:root@mongo:27017/

  electrosfi-backend:
    image: electrosfi-backend-prod:latest
    restart: always
    container_name: electrosfi-backend-prod
    build: ./services/electrosfi-base/electrosfi-backend-master/
    depends_on:
      - mongodb
    networks:
      - "kong-net"
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - DB_CONNECTION=mongodb://root:root@mongodb:27017/

  #python meep
  meep-simulator:
    container_name: meep-simulator
    image: electrosfi-meep-simulator-prod:latest
    build: ./services/electrosfi-base/pythonMeep-master/
    networks: 
      - "kong-net"
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    # volumes:
    #   - "./services/pythonMeep/util:/util"
    #   - "./services/pythonMeep/routes/index.js:/routes/index.js"
    #   - "./services/pythonMeep/storage/users:/storage/users:rw"


     # ngsolve
  ngsolve:
    container_name: ngsolve
    image: ngsolve:latest
    build: ./services/ngsolve-integration/
    restart: always
    networks:
      - "kong-net"
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 7000