version: "3.7"  # optional since v1.27.0

networks:
  kong-net:
    external: true

services:
  mongo:
    image: mongo
    restart: always
    networks:
      - kong-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - kong-net
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_URL=mongodb://root:root@mongo:27017/

  api:
    image: electrosfi-backend-prod:latest
    restart: always
    container_name: electrosfi-backend
    build: .
    networks:
      - kong-net
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - DB_CONNECTION=mongodb://root:root@mongo:27017/